# Generated by Django 3.2.5 on 2021-07-15 16:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='http://blabla.com/image.jpg', upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(help_text='Выберите цветовой HEX-код (пример: #FF0033)', max_length=200, validators=[django.core.validators.RegexValidator(regex='#[0-9a-fA-F]{6}')], verbose_name='Цвет'),
        ),
    ]
