# Generated by Django 3.2.5 on 2021-07-13 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_alter_recipeingredientsdetails_recipe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeingredientsdetails',
            options={'verbose_name': 'Ингридиент рецепта', 'verbose_name_plural': 'Ингридиенты рецепта'},
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, help_text='Добавьте изображение', null=True, upload_to='', verbose_name='Изображение'),
        ),
        migrations.CreateModel(
            name='RecipeFavourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.recipe', verbose_name='Рецепт')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_favourites', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
