# Generated by Django 3.2.5 on 2021-08-12 10:39

import colorfield.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210726_1507'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userfollow',
            options={'verbose_name': 'Подписки на авторов', 'verbose_name_plural': 'Подписки на авторов'},
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.CharField(help_text='Введите единицу измерения ингредиента', max_length=200, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(help_text='Введите время приготовления в минутах', validators=[django.core.validators.MinValueValidator(limit_value=1, message='Время приготовления должно быть не менее 1.')], verbose_name='Время приготовления (мин)'),
        ),
        migrations.AlterField(
            model_name='recipeingredientsdetails',
            name='amount',
            field=models.IntegerField(help_text='Введите количество', validators=[django.core.validators.MinValueValidator(limit_value=1, message='Количество должно быть не менее 1.')], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=colorfield.fields.ColorField(default='#888888', help_text='Выберите цветовой HEX-код (пример: #FF0033)', max_length=200, validators=[django.core.validators.RegexValidator(message='Цвет должен быть задан в формате hex-кода', regex='#[0-9a-fA-F]{6}')], verbose_name='Цвет'),
        ),
    ]
