# Generated by Django 3.2.5 on 2021-07-15 15:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_recipe_pub_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recipefavourite',
            unique_together={('user', 'recipe')},
        ),
    ]
