# Generated by Django 3.2.5 on 2021-07-26 15:07

import colorfield.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(help_text='Введите время приготовления в минутах', validators=[django.core.validators.MinValueValidator(limit_value=1, message='Значение должно быть не менее 1.')], verbose_name='Время приготовления (мин)'),
        ),
        migrations.AlterField(
            model_name='recipeingredientsdetails',
            name='amount',
            field=models.IntegerField(help_text='Введите количество', validators=[django.core.validators.MinValueValidator(limit_value=1, message='Значение должно быть не менее 1.')], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=colorfield.fields.ColorField(default='#888888', help_text='Выберите цветовой HEX-код (пример: #FF0033)', max_length=200, validators=[django.core.validators.RegexValidator(regex='#[0-9a-fA-F]{6}')], verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(help_text='Введите slug', unique=True, verbose_name='Slug'),
        ),
    ]
